### ISSUE TITLE
Add ion-sfu support

### ISSUE THREAD

**Issue by smf8** [snapp-incubator/ghodrat#1]
I'd be happy to add support for load testing of ion-sfu. If there are any considerations in mind regarding support of a new media server (in this case ion-sfu), please share :)

**Comment by mohammadne** [comment]
Hi @smf8 

sure, it would be awesome,
we are considering to add support for well-known WebRTC media servers.

**Comment by mohammadne** [comment]
HI @smf8 
we have added the support for `ion-sfu`
thanks for your contribution !
